---
- name: Installing required server packages
  become: true
  apt:
    pkg:
      - postgresql
    state: present
  when: needs_db_server
- name: Installing PostGIS required packages
  become: True
  apt:
    pkg:
      - postgis
    state: present
  when: needs_db_server and dbtype == 'postgis'
- name: Installing required client packages
  become: true
  apt:
    pkg:
      - build-essential
      - python3-dev
      - libpq-dev
      - postgresql-client
      - python3-psycopg2
    state: present
