---
galaxy_info:
  author: your name
  description: Redis server installation for Django-Q
  company: your company (optional)

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - redis
    - django
    - django-q
    - cache

dependencies: []
